### ISSUE TITLE
Traceback error on new DB

### ISSUE THREAD

**Issue by megadr01d** [rss2email/rss2email#126]
```
$ pip3 install rss2email
```

```
$ pip3 list

Package    Version
---------- ---------
feedparser 5.2.1
html2text  2020.1.16
pip        20.1.1
rss2email  3.12.1
setuptools 49.2.0
wheel      0.34.2
```

```
$ r2e new | r2e new <email>
```

```
Traceback (most recent call last):
  File "/usr/local/bin/r2e", line 5, in <module>
    rss2email.main.run()
  File "/usr/local/lib/python3.8/site-packages/rss2email/main.py", line 186, in run
    args.func(feeds=feeds, args=args)
  File "/usr/local/lib/python3.8/site-packages/rss2email/command.py", line 46, in new
    feeds.save()
  File "/usr/local/lib/python3.8/site-packages/rss2email/feeds.py", line 350, in save
    self._save_feeds()
  File "/usr/local/lib/python3.8/site-packages/rss2email/feeds.py", line 365, in _save_feeds
    self.datafile.close()  # release the lock
AttributeError: 'NoneType' object has no attribute 'close'
```

`rss2email.cfg` and `rss2email.json` are created successfully.

```
OS X El Capitan [10.11.6]
```

**Comment by megadr01d** [comment]
And then after sending 107 feeds by IMAP:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rss2email/email.py", line 223, in imap_send
    imap.append(mailbox, None, date, message_bytes)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 408, in append
    return self._simple_command(name, mailbox, flags, date_time)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 991, in _command
    while self._get_response():
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1050, in _get_response
    resp = self._get_line()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1160, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1022, in _command_complete
    typ, data = self._get_tagged_response(tag, expect_bye=logout)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1148, in _get_tagged_response
    self._get_response()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1050, in _get_response
    resp = self._get_line()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1160, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/r2e", line 5, in <module>
    rss2email.main.run()
  File "/usr/local/lib/python3.8/site-packages/rss2email/main.py", line 186, in run
    args.func(feeds=feeds, args=args)
  File "/usr/local/lib/python3.8/site-packages/rss2email/command.py", line 90, in run
    feed.run(send=args.send)
  File "/usr/local/lib/python3.8/site-packages/rss2email/feed.py", line 915, in run
    self._send(sender=sender, message=message)
  File "/usr/local/lib/python3.8/site-packages/rss2email/feed.py", line 874, in _send
    _email.send(sender=sender, recipient=self.to, message=message,
  File "/usr/local/lib/python3.8/site-packages/rss2email/email.py", line 376, in send
    imap_send(message=message, config=config, section=section)
  File "/usr/local/lib/python3.8/site-packages/rss2email/email.py", line 225, in imap_send
    imap.logout()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 633, in logout
    typ, dat = self._simple_command('LOGOUT')
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imaplib.py", line 1024, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.abort: command: LOGOUT => socket error: EOF
```

**Comment by megadr01d** [comment]
rss2email.cfg

```
[DEFAULT]
from = user@rss2email.invalid
user-agent = rss2email/__VERSION__ (__URL__)
use-8bit = False
force-from = False
use-publisher-email = False
name-format = {feed-title}: {author}
to = <email>
proxy = 
feed-timeout = 60
same-server-fetch-interval = 0
active = True
digest = False
date-header = False
date-header-order = modified, issued, created, expired
bonus-header = 
trust-guid = True
trust-link = False
reply-changes = False
encodings = US-ASCII, ISO-8859-1, UTF-8, BIG5, ISO-2022-JP
post-process = 
digest-post-process = 
html-mail = True
use-css = True
css = h1 {
	font: 18pt Georgia, "Times New Roman";
	}
	body {
	font: 12pt Arial;
	}
	a:link {
	font: 12pt Arial;
	font-weight: bold;
	color: #0000cc;
	}
	blockquote {
	font-family: monospace;
	}
	.header {
	background: #e0ecff;
	border-bottom: solid 4px #c3d9ff;
	padding: 5px;
	margin-top: 0px;
	color: red;
	}
	.header a {
	font-size: 20px;
	text-decoration: none;
	}
	.footer {
	background: #c3d9ff;
	border-top: solid 4px #c3d9ff;
	padding: 5px;
	margin-bottom: 0px;
	}
	border: solid 4px #c3d9ff;
	}
	margin-left: 5px;
	margin-right: 5px;
	}
unicode-snob = False
links-after-each-paragraph = False
body-width = 0
email-protocol = imap
sendmail = /usr/sbin/sendmail
smtp-auth = False
smtp-username = username
smtp-password = password
smtp-server = smtp.example.net
smtp-port = 465
smtp-ssl = False
imap-auth = True
imap-username = <username>
imap-password = <password>
imap-server = <server>
imap-port = <port>
imap-ssl = True
imap-mailbox = INBOX
maildir-path = ~/Maildir
maildir-mailbox = INBOX
verbose = info

[feed.feed-0]
url = https://www.comicsrss.com/rss/yaffle.rss

[feed.feed-1]
url = https://www.comicsrss.com/rss/yesimhotinthis.rss

[feed.feed-2]
url = https://www.comicsrss.com/rss/zackhill.rss

[feed.feed-3]
url = https://www.comicsrss.com/rss/zen-pencils.rss

[feed.feed-4]
url = https://www.comicsrss.com/rss/ziggy.rss

[feed.feed-5]
url = https://www.comicsrss.com/rss/zits.rss
```

**Comment by Ekleog** [comment]
@AndreyMZ @kaashif I think you are the two who last touched locking, and at least the first issue looks related to it. Do you have an idea what might be going on?

@megadr01d The second issue you reported looks like something that should be reported to `imaplib` upstream (and/or to your IMAP server, EOF before logout sounds weird). I don't think we'll be able to do much here, so I'd suggest you go ask there? On the first issue it's most likely an issue from here indeed

**Comment by jpiszcz** [comment]
Also running into the same issue:
AttributeError: 'NoneType' object has no attribute 'close'

Gustavo pointed out this issue (126) from the Debian team-- thread details:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1759122.html

Versions and how to reproduce:

Versions:
ii  python             2.7.17-2     amd64        interactive high-level object-$
ii  python3-bs4        4.9.1-1      all          error-tolerant HTML parser for$
ii  python3-feedparser 5.2.1-2      all          Universal Feed Parser for Pyth$
ii  python3-html2text  2020.1.16-1  all          Python module for converting H$
ii  rss2email          1:3.12.1-1     all          receive RSS feeds by email

rss2email 3.12.1-1
$ # clear out old preferences and start fresh
$ rm -f $HOME/.rss2email/feeds.dat \
>       $HOME/.config/rss2email.cfg \
>       $HOME/.local/share/rss2email.json
$ r2e new test@localhost
Traceback (most recent call last):
  File "/usr/bin/r2e", line 5, in <module>
    rss2email.main.run()
  File "/usr/lib/python3/dist-packages/rss2email/main.py", line 186, in run
    args.func(feeds=feeds, args=args)
  File "/usr/lib/python3/dist-packages/rss2email/command.py", line 46, in new
    feeds.save()
  File "/usr/lib/python3/dist-packages/rss2email/feeds.py", line 350, in save
    self._save_feeds()
  File "/usr/lib/python3/dist-packages/rss2email/feeds.py", line 365, in _save_feeds
    self.datafile.close()  # release the lock
AttributeError: 'NoneType' object has no attribute 'close'
$

rss2email 3.11-2
$ # clear out old preferences and start fresh
$ rm -f $HOME/.rss2email/feeds.dat \
>       $HOME/.config/rss2email.cfg \
>       $HOME/.local/share/rss2email.json
$ r2e new user@localhost
$
