### ISSUE TITLE
Fetching errors out on items with lines of >998 characters 

### ISSUE THREAD

**Issue by Mzyxptlk** [rss2email/rss2email#141]
With `email-protocol = smtp`, rss2email does not respect [SMTP's maximum line length of 998 octets (see 4.5.3.1.6)](https://datatracker.ietf.org/doc/rfc5321/?include_text=1). This results in the following error when an RSS feed contains an item with longer lines than that: 
```
Traceback (most recent call last):
  File "/usr/bin/r2e", line 5, in <module>
    rss2email.main.run()
  File "/usr/lib/python3/dist-packages/rss2email/main.py", line 186, in run
    args.func(feeds=feeds, args=args)
  File "/usr/lib/python3/dist-packages/rss2email/command.py", line 90, in run
    feed.run(send=args.send)
  File "/usr/lib/python3/dist-packages/rss2email/feed.py", line 915, in run
    self._send(sender=sender, message=message)
  File "/usr/lib/python3/dist-packages/rss2email/feed.py", line 874, in _send
    _email.send(sender=sender, recipient=self.to, message=message,
  File "/usr/lib/python3/dist-packages/rss2email/email.py", line 372, in send
    smtp_send(
  File "/usr/lib/python3/dist-packages/rss2email/email.py", line 193, in smtp_send
    smtp.send_message(message, sender, recipient.split(','))
  File "/usr/lib/python3.8/smtplib.py", line 970, in send_message
    return self.sendmail(from_addr, to_addrs, flatmsg, mail_options,
  File "/usr/lib/python3.8/smtplib.py", line 892, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'maximum allowed line length is 998 octets, got 1308')
```

[This](https://www.escapistmagazine.com/v2/category/zero-punctuation/feed/) is an example of a feed featuring such items. That feed comes very late in my configuration, so I can't tell if it prevents subsequent feeds from being retrieved.

MTAs (some? many? all?) can be configured to allow longer lines (I've seen it in Exim, at least), but I don't think rss2email should depend on such non-standard behaviour.

**Comment by Ekleog** [comment]
FWIW, in practice MTAs are usually more around 64k bytes per line than the 998 from the RFC — that being said, rss2email should definitely not depend on it, but I just want to say that if your MTA rejects lines longer than 998 you probably will have issues with lots of things besides rss2email :)
