### ISSUE TITLE
rss2email cannot run on Python 3.5.x

### ISSUE THREAD

**Issue by monperrus** [rss2email/rss2email#155]
FTR, the latest version of rss2email cannot run on Python 3.5.x because dependency feedparser requires at least 3.6.

Pasting the error for referencing by Google and closing the issue.

```
Traceback (most recent call last):
  File "/home/martin/bin/r2e", line 7, in <module>
    import rss2email.main
  File "/home/martin/bin/rss2email/main.py", line 28, in <module>
    from . import command as _command
  File "/home/martin/bin/rss2email/command.py", line 30, in <module>
    from . import error as _error
  File "/home/martin/bin/rss2email/error.py", line 28, in <module>
    import feedparser as _feedparser
  File "/home/martin/.local/lib/python3.5/site-packages/feedparser/__init__.py", line 31, in <module>
    from .api import parse
  File "/home/martin/.local/lib/python3.5/site-packages/feedparser/api.py", line 56, in <module>
    from . import http
  File "/home/martin/.local/lib/python3.5/site-packages/feedparser/http.py", line 156
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'
```
                                                             ^

**Comment by auouymous** [comment]
And rss2email also requires 3.6 since https://github.com/rss2email/rss2email/pull/149/commits/ba4c3dbbaf769babb656a797691e0bb8edd8d53a.
