### ISSUE TITLE
AttributeError: 'TimeLimitedFunction' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by LorenRiccie** [rss2email/rss2email#184]
r2e run --no-send

Traceback (most recent call last):
  File "/usr/local/bin/r2e", line 5, in <module>
    rss2email.main.run()
  File "/usr/local/lib/python3.9/site-packages/rss2email/main.py", line 163, in run
    args.func(feeds=feeds, args=args)
  File "/usr/local/lib/python3.9/site-packages/rss2email/command.py", line 62, in run
    feed.run(send=args.send)
  File "/usr/local/lib/python3.9/site-packages/rss2email/feed.py", line 836, in run
    parsed = self._fetch()
  File "/usr/local/lib/python3.9/site-packages/rss2email/feed.py", line 350, in _fetch
    return f(self.url, self.etag, modified=self.modified, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rss2email/util.py", line 77, in __call__
    elif self.isAlive():
AttributeError: 'TimeLimitedFunction' object has no attribute 'isAlive'

**Comment by auouymous** [comment]
This was fixed by d2fca1c5f84162f1a81abf5a7067c2e765b4a5a4 in 3.13.

**Comment by amiryal** [comment]
Actually in [v3.12](https://github.com/rss2email/rss2email/compare/v3.11...v3.12). Maybe better stick to 3.12.3 until we [stabilise 3.13 a bit](https://github.com/rss2email/rss2email/pull/183).

**Comment by LorenRiccie** [comment]
Thanks for the quick answer!
v. 3.12.3 fixed the issue. Got back my feeds :)
