### ISSUE TITLE
ValueError: invalid interpolation syntax

### ISSUE THREAD

**Issue by xrat** [rss2email/rss2email#197]
Using r2e 3.13.1 I get the error `ValueError: invalid interpolation syntax in 'https://odysee.com/$/rss/@drsambailey:c' at position 19` when I try to add the respective RSS feed. My actual command line

```
r2e add _med.sambailey 'https://odysee.com/$/rss/@drsambailey:c'
```

Full version:

```
$ r2e --full-version
rss2email 3.13.1
python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
feedparser 6.0.5
html2text (2020, 1, 16)
```

Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/r2e", line 5, in <module>
    rss2email.main.run()
  File "/home/user/.local/lib/python3.7/site-packages/rss2email/main.py", line 199, in run                                                                        
    args.func(feeds=feeds, args=args)
  File "/home/user/.local/lib/python3.7/site-packages/rss2email/command.py", line 64, in add                                                                      
    feeds.save()
  File "/home/user/.local/lib/python3.7/site-packages/rss2email/feeds.py", line 326, in save                                                                      
    feed.save_to_config()
  File "/home/user/.local/lib/python3.7/site-packages/rss2email/feed.py", line 291, in save_to_config                                                             
    self.config[self.section] = data
  File "/usr/lib/python3.7/configparser.py", line 971, in __setitem__
    self.read_dict({key: value})
  File "/usr/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/lib/python3.7/configparser.py", line 1198, in set
    super().set(section, option, value)
  File "/usr/lib/python3.7/configparser.py", line 893, in set
    value)
  File "/usr/lib/python3.7/configparser.py", line 463, in before_set
    "position %d" % (value, tmp_value.find('$')))
ValueError: invalid interpolation syntax in 'https://odysee.com/$/rss/@drsambailey:c' at position 19
```

**Comment by xrat** [comment]
With the patch I was able to add the feed, and I successfully ran my ~250 other feeds without issues, too. Thanks a lot!

**Comment by Ekleog** [comment]
@auouymous This… looks like something that totally makes sense, I have no idea why we're currently doing extended interpolation. Would you mind sending this patch as a PR with a big backwards compatibility warning in the changelog? :)
