### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by raspbeguy** [rss2email/rss2email#211]
I'm trying to package rss2email for Alpine Linux. I tried to run the unittests, but it seems they are failing:

```
..................................FFFFF
======================================================================
FAIL: test_default (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ggodfroy/repo/rss2email/test/test_reply_changes.py", line 34, in test_default
    self.assertEqual(1, len(messages))
AssertionError: 1 != 0

======================================================================
FAIL: test_no_send (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ggodfroy/repo/rss2email/test/test_reply_changes.py", line 92, in test_no_send
    self.assertEqual(2, len(messages))
AssertionError: 2 != 0

======================================================================
FAIL: test_off (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ggodfroy/repo/rss2email/test/test_reply_changes.py", line 43, in test_off
    self.assertEqual(1, len(messages))
AssertionError: 1 != 0

======================================================================
FAIL: test_on (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ggodfroy/repo/rss2email/test/test_reply_changes.py", line 52, in test_on
    self.assertEqual(2, len(messages))
AssertionError: 2 != 0

======================================================================
FAIL: test_switch (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ggodfroy/repo/rss2email/test/test_reply_changes.py", line 76, in test_switch
    self.assertEqual(2, len(messages))
AssertionError: 2 != 0

----------------------------------------------------------------------
Ran 39 tests in 8.950s
```

Sadly I can't go further in packaging before those tests being passed. Do you know where it comes from?

**Comment by auouymous** [comment]
They work for me. Do you have python 3.6+, and feedparser 6.0.5+?

`test/util/tempmaildir.py` creates a maildir directory and `test/test_reply_changes.py` sends an email which should be stored in the maildir. In your case, that maildir is always empty after each test runs r2e. I don't know how to make the unittests output messages produced by r2e to begin debugging where the problem is for you.

Could you try the following?

Copy this to a `.config` file in the test/ directory of rss2email source.
```
[DEFAULT]
to = mbox@mail.example
email-protocol = maildir
maildir-path = .maildir
maildir-mailbox = inbox
[feed.test-feed]
url = file:data/nodejs/feed1.xml
```

cd test
mkdir -p .maildir/inbox/tmp
mkdir -p .maildir/inbox/new
../r2e -c .config -d .data run

If successful, it will create a file in .maildir/inbox/new/, if not, it will tell you why it couldn't.

You can then remove `.config`, `.data` and `.maildir` from the test directory.

**Comment by amiryal** [comment]
It may also help if you describe the environment and include the steps you took to run the unittests. There are instructions in `test/README`, and as a reference there is one way prescribed in `.github/workflows/python-package.yml`:
```
python -m pip install --upgrade pip
pip install poetry
poetry install
cd ./test
poetry run python -m unittest
```

**Comment by raspbeguy** [comment]
I did my tests on Archlinux, which has python 3.10.2 but feedparser 6.0.2 only. So I think that's the reason.
Did the test on Alpine edge, with python 3.10.2 and feedparser 6.0.8, works correctly.

Sorry for the noise.
