### ISSUE TITLE
[3.14] Fails tests with html2text >=2024.2.25

### ISSUE THREAD

**Issue by hartwork** [rss2email/rss2email#254]
Hi!

It has [come to my attention](https://bugs.gentoo.org/926133) that the tests of rss2email 3.14 started failing and playing with the failure revealed that use with html2text >=2024.2.25 breaks the tests while with html2text 2020.1.16 the tests pass. This may need a fix in either rss2email or html2text; looks more like html2text to me from a quick look, but please see for yourself below:

```console
# python --version
Python 3.10.13

# ( cd test && poetry run python -m unittest )
EEEEEEE...................................
======================================================================
ERROR: test_email_data/allthingsrss/1.config (test.TestEmails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 62, in fn
    self.run_single_test(config_path=test_path)
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 154, in run_single_test
    raise ValueError(
ValueError: error processing data/allthingsrss/1.config
--- expected
+++ generated
@@ -74,7 +74,7 @@
 
 Through `r2e pause _n_` where _n_ is a feed number, you can temporarily
 suspend checking that feed for new content. To start checking it again, simply
-run `r2e unpause _n_`. When you `r2e list`, an asterisk indicates that the
+run `r2e unpause  _n_`. When you `r2e list`, an asterisk indicates that the
 feed is currently unpaused and active.
 
 [![](http://feedads.g.doubleclick.net/~a/nYgTsIUsS9pmvRZ6092XGGHnNKg/0/di)](http://feedads.g.doubleclick.net/~a/nYgTsIUsS9pmvRZ6092XGGHnNKg/0/da)  

======================================================================
ERROR: test_email_data/allthingsrss/2.config (test.TestEmails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 62, in fn
    self.run_single_test(config_path=test_path)
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 154, in run_single_test
    raise ValueError(
ValueError: error processing data/allthingsrss/2.config
--- expected
+++ generated
@@ -74,7 +74,7 @@
 
 through `r2e pause _n_` where _n_ is a feed number, you can temporarily
 suspend checking that feed for new content. to start checking it again, simply
-run `r2e unpause _n_`. when you `r2e list`, an asterisk indicates that the
+run `r2e unpause  _n_`. when you `r2e list`, an asterisk indicates that the
 feed is currently unpaused and active.
 
 [![](http://feedads.g.doubleclick.net/~a/nygtsiuss9pmvrz6092xgghnnkg/0/di)](http://feedads.g.doubleclick.net/~a/nygtsiuss9pmvrz6092xgghnnkg/0/da)  

======================================================================
ERROR: test_email_data/allthingsrss/3.config (test.TestEmails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 62, in fn
    self.run_single_test(config_path=test_path)
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 154, in run_single_test
    raise ValueError(
ValueError: error processing data/allthingsrss/3.config
--- expected
+++ generated
@@ -76,7 +76,7 @@
 
 Through `r2e pause _n_` where _n_ is a feed number, you can
 temporarily suspend checking that feed for new content. To start
-checking it again, simply run `r2e unpause _n_`. When you `r2e list`,
+checking it again, simply run `r2e unpause  _n_`. When you `r2e list`,
 an asterisk indicates that the feed is currently unpaused and active.
 
 [![](http://feedads.g.doubleclick.net/~a/nYgTsIUsS9pmvRZ6092XGGHnNKg/0/di)](http://feedads.g.doubleclick.net/~a/nYgTsIUsS9pmvRZ6092XGGHnNKg/0/da)  

======================================================================
ERROR: test_email_data/allthingsrss/4.config (test.TestEmails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 62, in fn
    self.run_single_test(config_path=test_path)
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 154, in run_single_test
    raise ValueError(
ValueError: error processing data/allthingsrss/4.config
--- expected
+++ generated
@@ -76,7 +76,7 @@
 
 Through `r2e pause _n_` where _n_ is a feed number, you can
 temporarily suspend checking that feed for new content. To start
-checking it again, simply run `r2e unpause _n_`. When you `r2e list`,
+checking it again, simply run `r2e unpause  _n_`. When you `r2e list`,
 an asterisk indicates that the feed is currently unpaused and active.
 
 [![](http://feedads.g.doubleclick.net/~a/nYgTsIUsS9pmvRZ6092XGGHnNKg/0/di)](http://feedads.g.doubleclick.net/~a/nYgTsIUsS9pmvRZ6092XGGHnNKg/0/da)  

======================================================================
ERROR: test_email_data/allthingsrss/5.config (test.TestEmails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 62, in fn
    self.run_single_test(config_path=test_path)
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 154, in run_single_test
    raise ValueError(
ValueError: error processing data/allthingsrss/5.config
--- expected
+++ generated
@@ -96,7 +96,7 @@
 
 Through `r2e pause _n_` where _n_ is a feed number, you can
 temporarily suspend checking that feed for new content. To start
-checking it again, simply run `r2e unpause _n_`. When you `r2e list`,
+checking it again, simply run `r2e unpause  _n_`. When you `r2e list`,
 an asterisk indicates that the feed is currently unpaused and active.
 
 [![][4]][5]  

======================================================================
ERROR: test_email_data/allthingsrss/6.config (test.TestEmails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 62, in fn
    self.run_single_test(config_path=test_path)
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 154, in run_single_test
    raise ValueError(
ValueError: error processing data/allthingsrss/6.config
--- expected
+++ generated
@@ -86,7 +86,7 @@
 
 Through `r2e pause _n_` where _n_ is a feed number, you can
 temporarily suspend checking that feed for new content. To start
-checking it again, simply run `r2e unpause _n_`. When you `r2e list`,
+checking it again, simply run `r2e unpause  _n_`. When you `r2e list`,
 an asterisk indicates that the feed is currently unpaused and active.
 
 [![][4]][5]  

======================================================================
ERROR: test_email_data/allthingsrss/7.config (test.TestEmails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 62, in fn
    self.run_single_test(config_path=test_path)
  File "/tmp/tmp.TYWrzixNNK/rss2email/test/test.py", line 154, in run_single_test
    raise ValueError(
ValueError: error processing data/allthingsrss/7.config
--- expected
+++ generated
@@ -74,7 +74,7 @@
 
 Through `r2e pause _n_` where _n_ is a feed number, you can temporarily
 suspend checking that feed for new content. To start checking it again, simply
-run `r2e unpause _n_`. When you `r2e list`, an asterisk indicates that the
+run `r2e unpause  _n_`. When you `r2e list`, an asterisk indicates that the
 feed is currently unpaused and active.
 
 [![](http://feedads.g.doubleclick.net/~a/nYgTsIUsS9pmvRZ6092XGGHnNKg/0/di)](http://feedads.g.doubleclick.net/~a/nYgTsIUsS9pmvRZ6092XGGHnNKg/0/da)  

----------------------------------------------------------------------
Ran 42 tests in 21.546s

FAILED (errors=7)
```

**Comment by auouymous** [comment]
https://github.com/Alir3z4/html2text/issues/412#issuecomment-1986232413

**Comment by auouymous** [comment]
Fixed by https://github.com/rss2email/rss2email/commit/b5c0e78006c2db6929b5ff50e8529de58a00412a.

**Comment by hartwork** [comment]
@auouymous thank you! :+1:
