### ISSUE TITLE
Line too long

### ISSUE THREAD

**Issue by cmh716** [rss2email/rss2email#259]
rss2email 3.14

I have one feed,
http://feeds.macrumors.com/MacRumors-All

that will occasionally error on r2e with this error:

Traceback (most recent call last):
  File "/usr/local/bin/r2e", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/local/lib/python3.12/site-packages/rss2email/main.py", line 204, in run
    args.func(feeds=feeds, args=args)
  File "/usr/local/lib/python3.12/site-packages/rss2email/command.py", line 97, in run
    feed.run(send=args.send, clean=args.clean)
  File "/usr/local/lib/python3.12/site-packages/rss2email/feed.py", line 969, in run
    self._send(sender=sender, message=message)
  File "/usr/local/lib/python3.12/site-packages/rss2email/feed.py", line 918, in _send
    _email.send(recipient=self.to, message=message,
  File "/usr/local/lib/python3.12/site-packages/rss2email/email.py", line 435, in send
    smtp_send(
  File "/usr/local/lib/python3.12/site-packages/rss2email/email.py", line 224, in smtp_send
    smtp.send_message(message, config.get(section, 'from'), recipient.split(','))
  File "/usr/local/lib/python3.12/smtplib.py", line 975, in send_message
    return self.sendmail(from_addr, to_addrs, flatmsg, mail_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 897, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (500, b'Line too long (see RFC5321 4.5.3.1.6)')

Email "server" is a custom script using aiosmtpd, which seems to require adherence to RFC5321. Would you happen to have any tips on how to avoid this issue?  All I can do now is pause this feed, run r2e run for my other feeds, then r2e run --no-send to skip the bad entries.

Thanks

**Comment by cmh716** [comment]
I don't know if this is okay or not, but I fixed the issue with this code change:

https://github.com/rss2email/rss2email/pull/260/files

I'll defer to you guys as you're the experts on rss2email.  Thanks

**Comment by JulienPalard** [comment]
I don't think it's needed to re-implement line wrapping. "just" changing the Content-Transfer-Encoding to something like base64 should do.

I'll try this.
