### ISSUE TITLE
rss2email stopped working - json decode error with extra data

### ISSUE THREAD

**Issue by xplreitr** [rss2email/rss2email#55]
rss2email was working for many weeks. However, it just stopped recently reporting the following error in its logs

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rss2email/feeds.py", line 276, in _load_feeds
    data = _json.load(self._datafile_lock)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1396 column 1 (char 68924)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/r2e", line 5, in <module>
    rss2email.main.run()
  File "/usr/lib/python3/dist-packages/rss2email/main.py", line 168, in run
    feeds.load(lock=lock)
  File "/usr/lib/python3/dist-packages/rss2email/feeds.py", line 245, in load
    self._load_feeds(lock=lock, require=require)
  File "/usr/lib/python3/dist-packages/rss2email/feeds.py", line 279, in _load_feeds
    data = self._load_pickled_data(self._datafile_lock)
  File "/usr/lib/python3/dist-packages/rss2email/feeds.py", line 322, in _load_pickled_data
    feeds = list(feed.get_state() for feed in _pickle.load(f))
_pickle.UnpicklingError: invalid load key, '{'.
```
I am pretty new at debugging python, but from my understanding, there is extra data in line 1396, but I don't know in which file line 1396 is creating a problem.

**Comment by Ekleog** [comment]
I would guess it is `db.json`, that is at a place dependent on your setup. Potentially you had a power failure during rewriting of this file? Arguably the overwriting should be made atomic, but I'm not sure whether that's currently the case.

**Comment by Profpatsch** [comment]
Eh, one more reason to go back to a real database backend :(

**Comment by xplreitr** [comment]
Thanks Ekleog for pointing me in the right direction. After deleting the extraneous information, everything is back on track. Just for the reference of anyone who runs up against the same problem, in my case the json was named 'rss2email.db' and it was located in /home/user/.local/share
